/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class VentanaDetallesArmas extends javax.swing.JFrame {

    DefaultTableModel tabla;

    /**
     * Creates new form ventanaDetallesObjetos
     */
    public VentanaDetallesArmas() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        jLabelNombre.setText("<html><p align='center' margin-top=2em;>" + "DESCRIPCION " + "</p></html>");
    }

    public void estableceTabla(DefaultTableModel _tabla) {
        tabla = _tabla;
        jTableObjetos.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableObjetos = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTNombre = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelTNombre1 = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabelTNombre2 = new javax.swing.JLabel();
        jLabelNombre3 = new javax.swing.JLabel();
        jLabelTNombre3 = new javax.swing.JLabel();
        jLabelNombre4 = new javax.swing.JLabel();
        jLabelTNombre4 = new javax.swing.JLabel();
        jLabelNombre5 = new javax.swing.JLabel();
        jLabelTNombre5 = new javax.swing.JLabel();
        jLabelNombre6 = new javax.swing.JLabel();
        jLabelTNombre6 = new javax.swing.JLabel();
        jLabelNombre7 = new javax.swing.JLabel();
        jLabelTNombre7 = new javax.swing.JLabel();
        jLabelNombre8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(190, 31, 44));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableObjetos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 659, 130));

        jLabelNombre.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 650, 170));

        jLabelTNombre.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre.setText("Nombre");
        getContentPane().add(jLabelTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 320, -1));

        jLabelNombre1.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre1.setText("Caladrel");
        jLabelNombre1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 80, 20));

        jLabelTNombre1.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre1.setText("Peso");
        getContentPane().add(jLabelTNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 80, -1));

        jLabelNombre2.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre2.setText("Caladrel");
        jLabelNombre2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 80, 20));

        jLabelTNombre2.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre2.setText("Daño P");
        getContentPane().add(jLabelTNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, -1));

        jLabelNombre3.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre3.setText("Caladrel");
        jLabelNombre3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 80, 20));

        jLabelTNombre3.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre3.setText("Daño M");
        getContentPane().add(jLabelTNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 80, -1));

        jLabelNombre4.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre4.setText("Caladrel");
        jLabelNombre4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 80, 20));

        jLabelTNombre4.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre4.setText("Critico");
        getContentPane().add(jLabelTNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, -1));

        jLabelNombre5.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre5.setText("Caladrel");
        jLabelNombre5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 80, 20));

        jLabelTNombre5.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre5.setText("Rango");
        getContentPane().add(jLabelTNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 80, -1));

        jLabelNombre6.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre6.setText("Caladrel");
        jLabelNombre6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, -1));

        jLabelTNombre6.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre6.setText("Tipo");
        getContentPane().add(jLabelTNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, 10));

        jLabelNombre7.setFont(new java.awt.Font("Pokemon Classic", 0, 10)); // NOI18N
        jLabelNombre7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre7.setText("Caladrel");
        jLabelNombre7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, 20));

        jLabelTNombre7.setFont(new java.awt.Font("Pokemon Classic", 0, 8)); // NOI18N
        jLabelTNombre7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTNombre7.setText("Especial");
        getContentPane().add(jLabelTNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 80, -1));

        jLabelNombre8.setFont(new java.awt.Font("Pokemon Classic", 0, 12)); // NOI18N
        jLabelNombre8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre8.setText("Caladrel");
        jLabelNombre8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 320, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDetallesArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDetallesArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDetallesArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDetallesArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDetallesArmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JLabel jLabelNombre5;
    private javax.swing.JLabel jLabelNombre6;
    private javax.swing.JLabel jLabelNombre7;
    private javax.swing.JLabel jLabelNombre8;
    private javax.swing.JLabel jLabelTNombre;
    private javax.swing.JLabel jLabelTNombre1;
    private javax.swing.JLabel jLabelTNombre2;
    private javax.swing.JLabel jLabelTNombre3;
    private javax.swing.JLabel jLabelTNombre4;
    private javax.swing.JLabel jLabelTNombre5;
    private javax.swing.JLabel jLabelTNombre6;
    private javax.swing.JLabel jLabelTNombre7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableObjetos;
    // End of variables declaration//GEN-END:variables
}
